# Generated by Django 4.1.4 on 2023-09-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_authhor_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_post",
            new_name="date_posted",
        ),
    ]
